name: GoExtractor Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'GoExtractor/**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.x'

    - name: Run Tests
      run: cd GoExtractor && go test ./...

